#################################################
# SERVER
#################################################
server.port=${PORT:8080}

#################################################
# DATABASE (Aiven MySQL)
#################################################
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
spring.jpa.hibernate.ddl-auto=update

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

#################################################
# CONNECTION POOL
#################################################
spring.datasource.hikari.maximum-pool-size=10
spring.datasource.hikari.minimum-idle=2
spring.datasource.hikari.connection-timeout=30000

#################################################
# THYMELEAF
#################################################
spring.thymeleaf.cache=false

#################################################
# FILE UPLOAD
#################################################
spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB

upload.path=uploads/products/

#################################################
# TWILIO
#################################################
twilio.account.sid=
twilio.auth.token=
twilio.verify.service.sid=

#################################################
# GMAIL SMTP
#################################################
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=${MAIL_USERNAME}
spring.mail.password=${MAIL_PASSWORD}

spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true